#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage $0 [release-name] [values-file] [chart-dir]"
  exit 1
fi

set -x

helm status $1

if [ $? -ne 0 ]; then
  # doesn't exist yet
  echo "Release doesn't exist, installing"
  helm install --replace --name $1 --values $2 $3
else
  # already exists
  echo "Release already exists, upgrading"
  helm upgrade $1 --values $2 $3
fi
