#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage $0 [namespace] [release-name] [values-file] [chart-dir]"
  exit 1
fi

set -x

helm status $2

if [ $? -ne 0 ]; then
  # doesn't exist yet
  echo "Release doesn't exist, installing"
  helm install --namespace $1 --name $2 --values $3 $4
else
  # already exists
  echo "Release already exists, upgrading"
  helm upgrade $2 --values $3 $4 fi
fi
